### ISSUE TITLE
Bug: Error in C[i, j] : subscript out of bounds

### ISSUE THREAD

**Issue by ROldenburg** [audreyqyfu/mrpc#1]
Dear all,
MRPC seems to be a great project - although Im just about to learn about the theory.
In trying to explore what I can learn from this for the structure of my own data I got the following error message

Error in C[i, j] : subscript out of bounds
In addition: Warning messages:
1: In if (FDRcontrol == "LOND") { :
  the condition has length > 1 and only the first element will be used

The data set seems to be ok, at least I get a sensible graph out of it using the pcalg package. My function call looks like this
suffStat_RS = list(C = RobustCor(datscales, Beta=0.005)$RR, n = nrow(datscales))
resS= MRPC(data=datnum, suffStat=suffStat_RS, GV=0, FDR=0.1, indepTest='gaussCItest',
          labels=names(datnum), verbose = TRUE)

Any help on this? If you need I could send the data file and the complete script via mail.
Best wishes
Reinhard

**Comment by audreyqyfu** [comment]
Hi Reinhard,

Many thanks for your interest in MRPC and for trying out our package.  If you are using version 3.0.0, the argument FDRcontrol needs to be specified.  Otherwise, the MRPC function will aim to control the familywise type I error rate and look for the argument alpha.  You may try adding the following specification to the argument list: 
FDRcontrol = 'LOND'.  
You may also take a look at the examples in the documentation for the function MRPC().

Hope this helps.  Please feel free to contact us if you have additional questions.

Best,
Audrey
